name: SyncGithubToGiteeAllBranch
on:
  push:
    branches: [ master ]
  schedule:
  - cron: "0 18 * * *"

jobs:
 repo-sync: 
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the Github user repos to Gitee.
        uses: Yikun/hub-mirror-action@master
        with:
          src: 'github/TR-Yu'
          dst: 'gitee/TR-Yu'
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token:  ${{ secrets.GITEE_TOKEN }}
          clone_style: "ssh"
          force_update: true
          debug: true
          dst_visibility: 'private'
          timeout: '10m'
          static_list: "tools,notes,java-base-demo"
